# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 04:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaches',
            name='salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='section',
            name='day_of_lesson',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='section',
            name='teaches',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Teaches'),
        ),
    ]
