# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170513_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='total_lessons',
            field=models.IntegerField(default=36),
        ),
    ]
