# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_group_total_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='day_of_lesson',
            field=models.IntegerField(),
        ),
    ]
