# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170513_1713'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendance',
            new_name='TeacherAttendance',
        ),
        migrations.AlterModelOptions(
            name='teacherattendance',
            options={'verbose_name': 'TeacherAttendance', 'verbose_name_plural': 'TeacherAttendance'},
        ),
    ]
